;(function($){'use strict';$('.styler').styler();$('.contact-selector').find('select').on('change',function(){var url=$(this).val();window.location=url;});$('.popup-iframe').magnificPopup({disableOn:700,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:false,fixedContentPos:false});$('.popup-gallery').magnificPopup({delegate:'a',type:'image',tLoading:'Loading image #%curr%...',mainClass:'mfp-img-mobile',gallery:{enabled:true,navigateByImgClick:true,preload:[0,1]},image:{tError:'<a href="%url%">The image #%curr%</a> could not be loaded.',titleSrc:function(item){return item.el.attr('title');}}});var sameHeight=$('.same-height');if(sameHeight.length){sameHeight.matchHeight();$('a[data-toggle="tab"]').on('shown.bs.tab',function(e){sameHeight.matchHeight();})}
if($('#instafeed').length){var feed=new Instafeed({get:'user',userId:6863145583,limit:9,accessToken:'6863145583.3a81a9f.c22b798dffcd4f41a1d13f96b2b3baac',template:'<a href="{{link}}" target="_blank"><img src="{{image}}" /></a>'});feed.run();}
var gdprBlock=$('.gdpr-alert');var gdprButton=gdprBlock.find('button');var cookieName='gdpr';if(Cookies.get(cookieName)!=1){gdprBlock.fadeIn('fast');}
gdprButton.on('click',function(){Cookies.set(cookieName,1)
gdprBlock.fadeOut('fast');});$('.hero-slider').slick({dots:true,infinite:true,slidesToShow:1,autoplay:true,autoplaySpeed:4500,dotsClass:'list-unstyled slick-dots text-center',nextArrow:'<button type="button" class="slick-control slick-next"></button>',prevArrow:'<button type="button" class="slick-control slick-prev"></button>',appendDots:$('.hero-section'),responsive:[{breakpoint:1024,settings:{dots:false,arrows:false}}]});$("a[href*='#']").not('[data-toggle="tab"]').on('click',function(e){var target=$(this).attr('href');if($(target).length){e.preventDefault();$('html, body').animate({scrollTop:$(target).offset().top},500);}});if($(window).width()>992){var aniview=$('.aniview');aniview.each(function(){var el=$(this);if(el.is('[data-av-delay]')){var duration=el.attr('data-av-delay');el.css({'-webkit-animation-delay':duration+'s','animation-delay':duration+'s',});}});aniview.AniView();}
$.validator.addMethod("emailfull",function(value,element){return this.optional(element)||/^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i.test(value);});var forms=$('form');forms.each(function(){var form=$(this);var validator=form.validate({rules:{email:{required:true,emailfull:true}},messages:{name:"Please enter your name",email:"Please enter your email",comments:"Please enter your comments"},submitHandler:function(form){var formName=$(form).attr('name');var thanksSelector;var formURL;if(formName=='subscribe'){thanksSelector='#newsletter-thanks';formURL='integrations/subscribe.php';}else if(formName=='reservation'){thanksSelector='#reservation-thanks';formURL='integrations/reservation.php';}
$.ajax({url:formURL,type:"POST",data:$(form).serialize()}).done(function(){$.magnificPopup.open({items:{src:thanksSelector,},type:'inline'});});return false;},showErrors:function(errorMap,errorList){var i,elements,error;for(i=0;this.errorList[i];i++){if(i===0){error=this.errorList[i];if(this.settings.highlight){this.settings.highlight.call(this,error.element,this.settings.errorClass,this.settings.validClass);}
this.showLabel(error.element,error.message);}}
if(this.errorList.length){this.toShow=this.toShow.add(this.containers);}
if(this.settings.success){for(i=0;this.successList[i];i++){this.showLabel(this.successList[i]);}}
if(this.settings.unhighlight){for(i=0,elements=this.validElements();elements[i];i++){this.settings.unhighlight.call(this,elements[i],this.settings.errorClass,this.settings.validClass);}}
this.toHide=this.toHide.not(this.toShow);this.hideErrors();this.addWrapper(this.toShow).show();},errorPlacement:function(error,element){var stylerElement=element.parent().find('.jq-selectbox__select');if(stylerElement.length){error.insertAfter(stylerElement.parent());}else{error.insertAfter(element);}},invalidHandler:function(){setTimeout(function(){$('.styler').trigger('refresh');},1)}});});})($);